spring:
  profiles:
    active: development
  datasource:
    url: jdbc:sqlserver://localhost;database=Nutritionology;user=Denis_Nutrotionology;password=123456;encrypt=true;trustServerCertificate=true
  properties:
    hibernate:
      format_sql: true
      ddl-auto: update
  jpa:
    generate-ddl: true

server:
  port: 8081

upload:
  path: C:\Users\User\IdeaProjects\Nutritionology\src\uploads
